import React from 'react';
import LegalLayout from '../components/legal/LegalLayout';

const TermsPage = () => (
  <LegalLayout title="Terms of Service" updated="July 2026">
    <p>
      These terms govern use of Farik, a property management platform that lets landlords manage
      properties, tenants, rent collection, maintenance, and notices, including over SMS text
      messaging. By creating an account or using Farik, you agree to these terms.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">The service</h2>
    <p>
      Farik is provided to landlords ("Landlords") to manage their rental properties, and to the
      tenants of those Landlords ("Tenants") to view lease and payment information, submit
      maintenance requests, and communicate with their Landlord — including by text message.
      Farik is a software tool; the Landlord remains responsible for their relationship with
      their Tenants, including compliance with applicable residential tenancy law.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Accounts</h2>
    <p>
      You're responsible for the accuracy of information you provide and for keeping your login
      credentials secure. Landlords are responsible for having the right to add a Tenant's contact
      information to Farik and to communicate with that Tenant, including by SMS.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Payments</h2>
    <p>
      Rent payments processed through Farik are handled by a third-party payment processor.
      Farik records payment status but is not a bank or money transmitter. Fees, if any, will be
      disclosed before you're charged.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Text messaging</h2>
    <p>
      Farik sends SMS messages on behalf of Landlords for rent reminders, late notices,
      maintenance updates, and general communication with Tenants. Message and data rates may
      apply. See our <a href="/sms-consent" className="text-brand-600 hover:underline">SMS Policy</a> for
      opt-in and opt-out details.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Acceptable use</h2>
    <p>
      You agree not to use Farik to send unlawful, abusive, or unsolicited messages, or to use the
      service in a way that violates applicable law, including Saskatchewan and Canadian
      residential tenancy and privacy law.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Disclaimer & liability</h2>
    <p>
      Farik is provided "as is." Late notices and other documents generated by Farik are templates
      only and don't constitute legal advice — Landlords are responsible for ensuring notices they
      send comply with applicable law. To the extent permitted by law, Farik is not liable for
      indirect or consequential damages arising from use of the service.
    </p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Governing law</h2>
    <p>These terms are governed by the laws of the Province of Saskatchewan and the laws of Canada applicable therein.</p>

    <h2 className="text-lg font-semibold text-slate-900 pt-2">Contact us</h2>
    <p>
      Questions about these terms can be sent to{' '}
      <a href="mailto:support@farik.ca" className="text-brand-600 hover:underline">support@farik.ca</a>.
    </p>
  </LegalLayout>
);

export default TermsPage;
